<?php

namespace AppBundle\Repository;

/**
 * Les_ColocatairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Les_ColocatairesRepository extends \Doctrine\ORM\EntityRepository
{
}
