<?php

namespace AppBundle\Repository;

/**
 * Annonces_colocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Annonces_colocRepository extends \Doctrine\ORM\EntityRepository
{
}
